### ISSUE TITLE
Formatter prefers newline between assignment and function call even if call start would fit on same line.

### ISSUE THREAD

**Issue by hzeller** [google/xls#1194]
Consider this code: some function call that fits into one line with two parameters, the second has to be broken in to the second line:

```rust
fn fun_returning_tuple(a: u32, b: u32) -> (u32, u32) { (a, b) }

fn foo(some_value_somewhat_long: u32, another_one_of_these: u32) {
    let (some_tuple_element, other_tuple_element) = fun_returning_tuple(some_value_somewhat_long,
                                                                        another_one_of_these);
}
```

The formatter changes this to

```rust
fn fun_returning_tuple(a: u32, b: u32) -> (u32, u32) { (a, b) }

fn foo(some_value_somewhat_long: u32, another_one_of_these: u32) {
    let (some_tuple_element, other_tuple_element) =
        fun_returning_tuple(some_value_somewhat_long, another_one_of_these);
}
```

Both solutions fit into 100 characters and both use the same amount of vertical space, so technically they could be considered equivalent from the 'formatting score'.

Of course it is a matter of taste, but personally I'd prefer the first, as it gives the reader more context on the same line ('what is assigned') and more visual readability clues  (nicely aligned function parameters). Also it is less visually 'dense'.

**Comment by cdleary** [comment]
We discussed a bit in person and I wrote a bit on why we end up with the second choice in the change description of https://github.com/google/xls/commit/fa7f34c3a1207cf20bbf76f6c22b8d76c261da99 -- I'll inline it here for posterity:

> [T]he way things generally work right now is:
> 
> * Does it greedily fit on a single line? (flat mode)
> * If not, does it greedily fit on the next line when I indent? (flat-when-nested)
> * If not, ok let's go to "break mode" where it can be arbitrarily multi-line. (break mode)
> 
> Some things that look nicer may not be amenable to that structure used, but it
> nicely prevents any kind of choice enumeration scheme by doing it this way and
> it stays fast, and hopefully all still ends up pretty reasonable.

The challenge right now for the requested form is that it's what you get when you enter "break mode" emission for the RHS, and break mode could result in a RHS of arbitrary vertical line length. So the greedy approach tries to do: [inline, nested next line, break mode] in that order because the first two are precisely known quantities (1 line, 2 lines, arbitrary lines). We potentially could introduce more fancy pretty print combinators in the future, and potentially some choice-tradeoff machinery, but I think it'll be good to see how far we can get with our current set.

This is also a good reminder I should push the dslx-fmt design doc into markdown.

Will close this particular issue as WAI for the time being on account of what I described above, but appreciate the filing, we may revisit at some point if we want to prioritize refining the formatter capabilities further.
