### ISSUE TITLE
JIT/Interpreter miscompare, crasher c89a

### ISSUE THREAD

**Issue by meheff** [google/xls#224]
Looks like a select with a non-selected poison operand ultimately gets replaced with poison. Effectively this results in the result not being stored in the result buffer (store of poison gets removed by llvm?).

https://bugs.llvm.org/show_bug.cgi?id=48435

Potential workaround might be to guard overshifted values using if/then block rather than select depending on resolution of bug.

[crasher_c89a.tar.gz](https://github.com/google/xls/files/5656381/crasher_c89a.tar.gz)

**Comment by cdleary** [comment]
I think this is blocked on the LLVM issue which is still not yet resolved.

**Comment by meheff** [comment]
Might be a while before that LLVM bug is fixed as these poison problems are pretty pervasive and fixing them has performance implications. We might want to change the way we handle shifts in the meantime. Instead of using selects we should try if/then/else blocks. That may be less likely to run afoul of poison handling problems in LLVM.

**Comment by cdleary** [comment]
Sounds good to me, I guess we should do sooner rather than later if it can produce miscompiles. We'll have to figure out who can pick it up, @hongted @vincent-mirian-google could be interesting one to pick up if you want to learn more about the JIT and the LLVM IR builder API! (But we probably need to hop on it immediately given it can hypothetically cause faulty verification.)

**Comment by cdleary** [comment]
We said in a brief meeting today that @meheff was going to take this since it can lead to corruption if LLVM optimizes incorrectly. Thanks Mark!
