### ISSUE TITLE
Consider separate DSLX desugaring phase

### ISSUE THREAD

**Issue by RobSpringer** [google/xls#503]
Based on discussions on some outstanding CLs, it might be time to consider adding a standalone desugaring phase for DSLX. This has come up both in Proc development (Spawn effectively desugars into two function-like things) and trace_fmt! (which desugar to invocations/format macros).

This would obv. be a fair bit of work, but it really might clean up at least these two areas a bit.

**Comment by cdleary** [comment]
Some main considerations I'd bring up here are that a) ASTs don't make for particularly good "manipulatable" program representations, b) desugaring AST nodes into more AST nodes you have to start concerning yourself with what position information is synthetic vs "real" from the original program (and can be referred back to easily) i.e. in error messages, c) having a full IR for desugaring purposes seems quite overkill, and every layer of IR added is in some nominal sense a form of tax we have to pay for over time, so every layer introduced like that needs to pull its conceptual weight. I think probably having type information "nodes" that refer back to immutable AST nodes as a minimal layer on top could make sense for the use case originally described, but I don't think deductive type inference needs to actually manipulate the original AST program representation personally. If we feel strongly about this would be good to understand potential use cases / their upsides better.

For `trace_fmt!` in particular I think parse tree wise it's simply an invocation (the parser doesn't _really_ need to know that it's special) and its special handling as a variadic invocation can be deferred to typechecking time for detection / handling as with other builtins. I think originally Ravi wanted to make it its own parse node because it didn't share much of the typechecking complexity with a normal invocation (i.e. it didn't need to be checked for parametric instantiation and such), so carving out another node made the special handling of this "easier case" builtin invocation easy. Correct me if I'm getting that understanding wrong though!
