### ISSUE TITLE
Dependency can not accept due to the internet block, how to solve it?

### ISSUE THREAD

**Issue by changkaiyan** [google/xls#528]
The internet of my computer has been blocked, so the dependency can not accept.  Thus I can not build it. Does someone have some good solutions?

**Comment by cdleary** [comment]
Hi @changkaiyan -- more details are needed to help you with your issue. What command are you running, what OS, what dependency in particular is being blocked. Most dependencies are likely essential, since we don't take unnecessary dependencies, but I may be able to give abstract advice on ways to proceed.

**Comment by meheff** [comment]
Closing this. Feel free to reopen if you have more details to post.
