### ISSUE TITLE
riscv_simple.x example segfaults in the JIT

### ISSUE THREAD

**Issue by hmontero1205** [google/xls#78]
Found this while testing https://github.com/google/xls/pull/66. 

For what it's worth, the problematic function is `run_instruction()` and we manged to trace the execution in gdb up until it actually runs the compiled function. After that, we don't have any debugging symbols to use so we're stuck with reading assembly.

For now, I set `compare_jit=False` in `examples/BUILD`.

**Comment by RobSpringer** [comment]
I'm not able to reproduce this issue, at least as I understand how it's triggered.

I've set compare_jit to true for the riscv_simple dslx_test target, and when I run all tests in that dir (and, in fact all XLS dirs), internally and in OSS-land, I only see green.

Are there any missing repro steps or possibly-relevant system differences? Since Hans' internship has ended, I don't have a lot of hope that he's still monitoring this issue, but, just in case - is there some additional step to recreate that I missed?

**Comment by cdleary** [comment]
It could be we fixed that other bug we observed in the array concat tests via quickcheck?

Is there a way we can do an integrity check at the LLVM JIT level that we're not doing scalar operations on pointers to eliminate that whole category of potential mistake?

**Comment by nanavati** [comment]
While working on re-enabling the JIT for dslx_test (after the transition to the C++ interpreter), I was able to confirm that this is fixed (though the code demonstrating that isn't ready yet).
