### ISSUE TITLE
DSLX: suggestion: struct-vs-function parametric syntax looks inconsistent

### ISSUE THREAD

**Issue by rdob-ant** [google/xls#993]
Consider following code sample:
```
struct MyStruct<K:u32, N:u32> {
    foo: uN[K],
    bar: uN[N],
}

fn genfunc<K:u32, N:u32>() -> MyStruct<K, N> {
    MyStruct {
        foo: uN[K]:0,
        bar: uN[N]:0
    }
}

fn func() -> MyStruct<3, 4> {
    genfn<u32:3, u32:4>()
}
```

In above code, `func` function shows the discrepancy:
- when structure type annotation is used, type annotation of parametric arguments must be avoided (e.g. `MyStruct<u32:3, u32:4>` leads to an error)
- at the same time, when calling a parametric function, parametric arguments must be type-annotated (e.g. `genfn<3, 4>()` leads to an error).

Perhaps syntax of these two cases can be unified, i.e. to allow omitting type annotations in both places?

**Comment by cdleary** [comment]
Note that this is nominally a dup of https://github.com/google/xls/issues/978 -- the problem is that we're currently reusing the validation that's done for array dimensions, but really struct parametrics should be able to take values of any type and do constexpr expression evaluation on them (they should not have all the same constraints as array dimensions).
